apiVersion: apps/v1
kind: Deployment
metadata:
  name: sungwook-vuex-demo
  labels:
    app: sungwook-vuex-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sungwook-vuex-demo
  template:
    metadata:
      labels:
        app: sungwook-vuex-demo
    spec:
      containers:
      - name: vuex
        image: choisunguk/vuex-study:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sungwook-vuex-demo
spec:
  selector:
    app: sungwook-vuex-demo
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sungwook-vuex-demo
spec:
  rules:
  - host: choicloudlab.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sungwook-vuex-demo
            port:
              number: 80
